spring.application.name=url-shortener

# Redirect Web App settings
redirect.url.host=${URL_HOST:localhost}
redirect.url.port=${URL_PORT:8080}
redirect.url.length=${URL_LENGTH:6}

# Cors settings
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000}

# Database
# Connection string and credentials
spring.datasource.url=${DATASOURCE_URL:jdbc:h2:mem:testdb}
spring.datasource.driverClassName=${DATASOURCE_DRIVER:org.h2.Driver}
spring.datasource.username=${DATASOURCE_USERNAME:sa}
spring.datasource.password=${DATASOURCE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.sql.init.platform=${DATASOURCE_INIT_PLATFORM:h2}
spring.jpa.defer-datasource-initialization=true

# Enable the H2 web console browser interface
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true